# Generated by Django 3.1.2 on 2020-11-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suapintegration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suapuser',
            name='ano_ingresso',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Ano de ingresso'),
        ),
        migrations.AddField(
            model_name='suapuser',
            name='categoria',
            field=models.CharField(choices=[
                ('Não se aplica', 'Não se aplica'),
                ('Indeterminado', 'Indeterminado'),
                ('Docente', 'Docente'),
                ('Técnico Administrativo', 'Técnico Administrativo'),
                ('Estagiário', 'Estagiário')
            ], default='Não se aplica', max_length=255, verbose_name='Categoria do servidor'),
        ),
        migrations.AddField(
            model_name='suapuser',
            name='codigo_curso',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código do curso'),
        ),
        migrations.AddField(
            model_name='suapuser',
            name='periodo_ingresso',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Período de ingresso'),
        ),
        migrations.AddField(
            model_name='suapuser',
            name='tipo',
            field=models.CharField(choices=[
                ('Indeterminado', 'Indeterminado'),
                ('Aluno', 'Aluno'),
                ('Servidor', 'Servidor'),
                ('Terceiro', 'Terceiro')
            ], default='Indeterminado', max_length=255, verbose_name='Tipo de usuário'),
        ),
        migrations.AlterField(
            model_name='suapuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='suapuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Can user the admin site?', verbose_name='membro da equipe'),
        ),
    ]
